### ISSUE TITLE
Sometimes no output when hitting two "faulty" characters one after another

### ISSUE THREAD

**Issue by ad-on-is** [goloveychuk/ButterflyFixer#1]
Hi,

first of all, thank you a lot for this great work-around. 

Although it's working fine, I noticed that sometimes the "faulty" characters don't get triggered. Especially when hitting two of the faulties one after another.

ie: my faulties are "e" and "i".

When I type the word "nein" (german for "no") ... i get "nen" as a result. Also when typing the word "viel" (german for "much") i get "vil". 

Cheers,
Adis

**Comment by goloveychuk** [comment]
I'll add more logging to understand what events sequence is here. Because now it's hard to understand what is going on. 
I guess here typing fastly and you have like
1) keydown for "e"
2) keydown for "i"
3) keyup for "e"
4) keyup for "i"

And somewhere here some key is triggered once more. 
I'll ping you when I'll add logging.

**Comment by goloveychuk** [comment]
@ad-on-is 
run `bash debug.bash`

then send me seqence of events when problem was detected.
like this
```
2018-01-16 00:22:57.651 butterfly_fixer[13186:647709] ev_type: keyup, code: 36
2018-01-16 00:22:58.313 butterfly_fixer[13186:647709] ev_type: keydown, code: 2
d2018-01-16 00:22:58.417 butterfly_fixer[13186:647709] ev_type: keyup, code: 2
2018-01-16 00:22:58.990 butterfly_fixer[13186:647709] ev_type: keydown, code: 0
a2018-01-16 00:22:59.098 butterfly_fixer[13186:647709] ev_type: keyup, code: 0
2018-01-16 00:22:59.648 butterfly_fixer[13186:647709] ev_type: keydown, code: 3
f2018-01-16 00:22:59.739 butterfly_fixer[13186:647709] ev_type: keyup, code: 3
2018-01-16 00:23:00.296 butterfly_fixer[13186:647709] ev_type: keydown, code: 3
f2018-01-16 00:23:00.412 butterfly_fixer[13186:647709] ev_type: keyup, code: 3
2018-01-16 00:23:01.464 butterfly_fixer[13186:647709] ev_type: keydown, code: 3
f2018-01-16 00:23:01.543 butterfly_fixer[13186:647709] ev_type: keyup, code: 3
```
not all logs. Only I and E events and nearest
